<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all();

        // Comprehensive product data with real images, varied prices, and detailed descriptions
        $productData = [
            'Laptops' => [
                ['MacBook Air M2', 1299, 1499, 'https://smvkt.com/cdn/shop/files/Apple-macbook-air-m2-13-spacegrey-1_grande.webp?v=1715679892', 'Experience the power of Apple\'s M2 chip in this ultra-thin laptop. With up to 18 hours of battery life, stunning Retina display, and silent fanless design, the MacBook Air M2 delivers exceptional performance for work and creativity. Perfect for professionals and students alike.'],
                ['Dell XPS 13', 999, 1199, 'https://media.power-cdn.net/images/h-cba1e2d294aac389e7b1994922696cf1/products/4091793/4091793_3_600x600_w_g.webp', 'The Dell XPS 13 features an InfinityEdge display with minimal bezels, delivering an immersive viewing experience. Powered by Intel\'s latest processors, this premium ultrabook offers exceptional performance, all-day battery life, and a premium build quality that rivals the best in the industry.'],
                ['ThinkPad X1 Carbon', 1599, 1799, 'https://media.power-cdn.net/images/h-4d66e53000b630f5a07c1652f1e937bd/products/2297401/2297401_5_600x600_t_g.webp', 'Built for business professionals, the ThinkPad X1 Carbon combines legendary ThinkPad durability with cutting-edge technology. Featuring the world\'s best keyboard, military-grade durability, and enterprise security features. The perfect choice for executives and power users who demand reliability.'],
                ['HP Spectre x360', 1199, 1399, 'https://media.power-cdn.net/images/h-a169640802d31c8f1a4640b4b8f22cdf/products/1122064/1122064_5_600x600_w_g.webp', 'A versatile 2-in-1 convertible laptop that transforms from laptop to tablet mode effortlessly. The HP Spectre x360 features a stunning OLED display option, premium Bang & Olufsen audio, and powerful performance. Ideal for creative professionals who need flexibility and style.'],
                ['ASUS ZenBook Pro', 1899, 2099, 'https://dlcdnwebimgs.asus.com/gain/096bd769-b48d-41ea-9eb5-7d305aa8a6fe/', 'Designed for content creators and professionals, the ASUS ZenBook Pro delivers desktop-class performance in a portable form factor. Features a stunning 4K OLED display, powerful graphics, and innovative ScreenPad for enhanced productivity. The ultimate workstation on the go.'],
                ['Surface Laptop Studio', 1699, 1899, 'https://media.power-cdn.net/images/h-94e42081b5bcf8e840b62f408c387d8a/products/2570591/2570591_8_600x600_t_g.webp', 'Microsoft\'s most innovative laptop yet, featuring a unique hinge design that transforms from laptop to tablet to studio mode. Perfect for designers, artists, and creators who need precision input and powerful performance. Includes Surface Pen support and exceptional build quality.'],
                ['MacBook Pro 14 M3', 2199, 2399, 'https://www.power.dk/media/in3jlfv1/macbook-pro-m3-14.png?height=240&quality=80', 'The MacBook Pro 14 with M3 chip delivers pro-level performance for the most demanding tasks. Featuring a Liquid Retina XDR display, advanced camera system, and studio-quality microphones. Whether you\'re editing 8K video or running complex simulations, this machine handles it all.'],
                ['Razer Blade 15', 2299, 2599, 'https://media.power-cdn.net/images/h-b60fdb3aee88937e915fb8b0b2fd603c/products/1197251/1197251_1_600x600_t_g.webp', 'The ultimate gaming laptop that doesn\'t compromise on portability. The Razer Blade 15 packs desktop-class graphics in a sleek aluminum chassis. With a high-refresh-rate display, advanced cooling system, and customizable RGB keyboard, it\'s perfect for gamers and content creators.'],
                ['LG Gram 17', 1399, 1599, 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=640&h=480&fit=crop', 'Remarkably lightweight at under 3 pounds, the LG Gram 17 offers a massive 17-inch display in an ultra-portable package. Perfect for professionals who need screen real estate without the bulk. Features all-day battery life and military-grade durability standards.'],
                ['Acer Swift 3', 699, null, 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=640&h=480&fit=crop', 'An excellent value proposition for everyday computing needs. The Acer Swift 3 delivers solid performance, good battery life, and a premium design at an affordable price point. Perfect for students and budget-conscious professionals who don\'t want to compromise on quality.'],
            ],
            'Smartphones' => [
                ['iPhone 15 Pro', 999, 1199, 'https://media.power-cdn.net/images/h-a23cdf386fee61e1ba4b7bd31eeec07e/products/2668264/2668264_10_600x600_t_g.webp', 'Apple\'s most advanced iPhone yet, featuring the A17 Pro chip, titanium construction, and a revolutionary camera system with 5x optical zoom. The iPhone 15 Pro delivers pro-level photography, gaming performance, and all-day battery life in a stunning design.'],
                ['Samsung Galaxy S24', 899, 999, 'https://media.power-cdn.net/images/h-a23cdf386fee61e1ba4b7bd31eeec07e/products/2668264/2668264_10_600x600_t_g.webp', 'Samsung\'s flagship smartphone featuring AI-powered features, exceptional camera capabilities, and a stunning Dynamic AMOLED display. The Galaxy S24 offers premium performance, all-day battery, and innovative software features that enhance productivity and creativity.'],
                ['Google Pixel 8', 699, 799, 'https://roobotech.com.au/cdn/shop/files/Pixel8obsidian.jpg?v=1714801573', 'Pure Android experience with Google\'s best-in-class computational photography. The Pixel 8 features the Tensor G3 chip, exceptional low-light photography, and 7 years of software updates. Perfect for photography enthusiasts and those who value clean Android software.'],
                ['OnePlus 12', 799, 949, 'https://jo-cell.com/cdn/shop/files/oneplus-12-16gb512gb.webp?v=1713683334', 'Flagship performance at a competitive price. The OnePlus 12 features blazing-fast charging, smooth 120Hz display, and powerful Snapdragon processor. Known for its clean OxygenOS software and exceptional build quality. Never settle for less.'],
                ['iPhone 15 Pro Max', 1199, 1399, 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=640&h=480&fit=crop', 'The largest and most capable iPhone, featuring a massive 6.7-inch display, extended battery life, and the most advanced camera system Apple has ever created. Perfect for content creators, professionals, and anyone who wants the absolute best iPhone experience.'],
                ['Samsung Galaxy S24 Ultra', 1299, 1499, 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=640&h=480&fit=crop', 'The ultimate Android flagship with S Pen support, 200MP camera, and premium titanium build. The Galaxy S24 Ultra is designed for power users who demand the best in productivity, creativity, and performance. A true note-taking and creative powerhouse.'],
                ['Google Pixel 8 Pro', 999, 1199, 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=640&h=480&fit=crop', 'Google\'s premium smartphone with pro-level photography features, including Super Res Zoom and Night Sight. Features a large, vibrant display, all-day battery, and exclusive AI features. The perfect choice for photography enthusiasts and Android purists.'],
                ['OnePlus 12 Pro', 899, 1049, 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=640&h=480&fit=crop', 'Premium flagship with no compromises. Features premium materials, wireless charging, IP68 rating, and OnePlus\'s signature fast charging technology. Delivers flagship performance with OnePlus\'s unique design language and software experience.'],
                ['Xiaomi 14', 649, 749, 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=640&h=480&fit=crop', 'Flagship features at an incredible value. The Xiaomi 14 offers Leica-tuned cameras, powerful performance, and premium build quality. Perfect for users who want flagship features without the flagship price tag. Exceptional value proposition.'],
                ['Nothing Phone 2', 599, null, 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=640&h=480&fit=crop', 'Unique transparent design with Glyph interface that provides visual notifications. Features clean Nothing OS, good performance, and distinctive aesthetics. For users who want to stand out from the crowd with a truly unique smartphone experience.'],
            ],
            'Headphones' => [
                ['AirPods Pro 2', 249, 279, 'https://media.power-cdn.net/images/h-4815615e08ef1675c08a259bdf10e29e/products/1804024/1804024_3_600x600_w_g.webp', 'Apple\'s premium wireless earbuds with active noise cancellation and spatial audio. Features H2 chip for improved sound quality, adaptive transparency mode, and personalized spatial audio. Perfect for iPhone users who want the best wireless audio experience.'],
                ['Sony WH-1000XM4', 299, 349, 'https://media.power-cdn.net/images/h-94536e7672c3bd470375c23b3d98d16f/products/1106906/1106906_15_600x600_t_g.webp', 'Industry-leading noise cancellation technology that adapts to your environment. Features exceptional battery life, quick charge, and LDAC support for high-resolution audio. The gold standard for noise-cancelling headphones, perfect for travel and daily commutes.'],
                ['Bose QuietComfort', 329, 379, 'https://dantell.dk/images/Bose-QuietComfort-45-black-1.jpeg', 'Legendary comfort meets world-class noise cancellation. The Bose QuietComfort headphones feature plush ear cushions, excellent sound quality, and Bose\'s signature noise-cancelling technology. Designed for all-day comfort during long listening sessions.'],
                ['Sennheiser HD 660S', 449, 499, 'https://media.power-cdn.net/images/h-e28cad0af55de194acba97576838f6fe/products/1057166/1057166_7_600x600_t_g.webp', 'Audiophile-grade open-back headphones delivering exceptional soundstage and detail. Features Sennheiser\'s renowned driver technology for accurate, natural sound reproduction. Perfect for critical listening, music production, and audio enthusiasts who demand the best.'],
                ['AirPods Max', 479, 549, 'https://media.power-cdn.net/images/h-1b5db35a3af76265cca2f94e86cdec87/products/3614402/3614402_4_600x600_w_g.webp', 'Apple\'s premium over-ear headphones featuring spatial audio, active noise cancellation, and exceptional build quality. The aluminum design is both beautiful and durable. Perfect for iPhone users who want premium over-ear audio with seamless integration.'],
                ['Sony WH-1000XM5', 399, 449, 'https://media.power-cdn.net/images/h-0d66ad6626ad377f43daeaf02b0127d2/products/1478246/1478246_1_600x600_t_g.webp', 'The latest evolution of Sony\'s flagship noise-cancelling headphones. Features improved noise cancellation, better sound quality, and refined design. Includes advanced features like speak-to-chat and multipoint pairing. The best noise-cancelling headphones Sony has ever made.'],
                ['Bose 700', 349, 399, 'https://media.power-cdn.net/images/h-759e54aca43d5ce1f29afe13f1ba32d0/products/1019225/1019225_4_600x600_t_g.webp', 'Sleek design meets powerful noise cancellation. The Bose 700 features 11 levels of noise cancellation, excellent call quality with noise-rejecting microphones, and touch controls. Perfect for professionals who need great audio and crystal-clear calls.'],
                ['Audio-Technica ATH-M50x', 149, 169, 'https://r2.gear4music.com/media/16/165126/600/preview.jpg', 'Professional studio monitoring headphones trusted by audio engineers worldwide. Features exceptional clarity, accurate frequency response, and collapsible design. Perfect for music production, mixing, and critical listening. Outstanding value for professional audio work.'],
                ['JBL Live 660NC', 199, 249, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=640&h=480&fit=crop', 'Wireless headphones with active noise cancellation and JBL\'s signature sound. Features long battery life, comfortable fit, and JBL\'s Pure Bass sound. Great value for users who want quality noise cancellation without breaking the bank.'],
                ['Beats Studio Pro', 349, null, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=640&h=480&fit=crop', 'Premium wireless headphones with powerful bass and active noise cancellation. Features Apple\'s H1 chip for seamless integration, spatial audio support, and up to 40 hours of battery life. Perfect for users who love bass-heavy sound and Apple ecosystem integration.'],
            ],
            'Gaming' => [
                ['PlayStation 5', 499, 549, 'https://media.power-cdn.net/images/h-9be3b7b73ff7f7117da472fd6e29602f/products/2856454/2856454_1_600x600_w_g.webp', 'Next-generation gaming console with lightning-fast SSD, ray tracing, and 3D audio. The PS5 delivers stunning 4K gaming at up to 120fps, haptic feedback controllers, and exclusive titles. Experience gaming like never before with immersive graphics and revolutionary features.'],
                ['Xbox Series X', 499, 549, 'https://kosmosrenew.dk/cdn/shop/files/xbox-series-x-kosmos-renew-60987_grande.png?v=1746705894', 'Microsoft\'s most powerful console ever, featuring 12 teraflops of processing power, quick resume, and backward compatibility. The Xbox Series X delivers true 4K gaming, ray tracing, and access to Game Pass. Perfect for gamers who want the ultimate Xbox experience.'],
                ['Steam Deck', 399, 449, 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=640&h=480&fit=crop', 'Portable PC gaming handheld that lets you play your Steam library anywhere. Features a custom AMD APU, 7-inch touchscreen, and full PC gaming capabilities. Perfect for gamers who want console-quality gaming on the go with access to their entire Steam library.'],
                ['Nintendo Switch OLED', 349, 379, 'https://cdn.lomax.dk/images/t_item_large/f_auto/v1719652019/produkter/70205130_1/nintendo-switch-oled-64gb-hvid-1.jpg', 'Enhanced Nintendo Switch with vibrant 7-inch OLED display, improved speakers, and 64GB internal storage. Play at home on your TV or take your games anywhere. Features exclusive Nintendo titles and the flexibility of hybrid gaming. Perfect for families and Nintendo fans.'],
                ['PlayStation 5 Digital', 399, 449, 'https://zrep.dk/media/catalog/product/cache/8ce56cb874d008a231e9732ece31296b/u/n/untitled.png', 'Digital-only version of the PS5 without disc drive. Same powerful performance and features as the standard PS5, but designed for gamers who prefer digital downloads. Save money while enjoying all the next-gen gaming features PlayStation has to offer.'],
                ['Xbox Series S', 299, 329, 'https://media.power-cdn.net/images/h-c443267b1d20c1a17bc4ef505653f141/products/2664289/2664289_5_600x600_w_g.webp', 'Compact next-gen console perfect for 1440p gaming. The Xbox Series S delivers next-generation performance in a small form factor, quick resume, and Game Pass access. Ideal for gamers who want next-gen features at an affordable price point.'],
                ['Steam Deck OLED', 549, 599, 'https://techvers.eu/wp-content/uploads/2023/11/steam_deck_oled_512gb-1.jpg', 'Premium Steam Deck with vibrant OLED display, improved battery life, and faster Wi-Fi. Features the same powerful PC gaming capabilities with enhanced visuals and longer play sessions. The ultimate portable PC gaming experience with stunning display quality.'],
                ['Nintendo Switch Lite', 199, 229, 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=640&h=480&fit=crop', 'Dedicated handheld gaming device perfect for on-the-go gaming. Smaller, lighter, and more affordable than the standard Switch. Features the same great games but designed exclusively for portable play. Perfect for younger gamers and those who prefer handheld gaming.'],
                ['ROG Ally', 699, 799, 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=640&h=480&fit=crop', 'Windows 11 gaming handheld from ASUS ROG. Features AMD Ryzen Z1 Extreme processor, 120Hz display, and full Windows gaming compatibility. Play your entire PC game library on the go with console-like controls and PC power.'],
                ['Meta Quest 3', 499, 549, 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=640&h=480&fit=crop', 'Next-generation standalone VR headset with mixed reality capabilities. Features improved resolution, faster processor, and color passthrough for AR experiences. Perfect for VR gaming, fitness, and social experiences. The most advanced standalone VR headset available.'],
            ],
            'Tablets' => [
                ['iPad Pro 12.9', 1099, 1299, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=640&h=480&fit=crop', 'Apple\'s most powerful tablet featuring the M2 chip, stunning Liquid Retina XDR display, and support for Apple Pencil and Magic Keyboard. Perfect for creative professionals, video editors, and anyone who needs desktop-class performance in a tablet form factor.'],
                ['iPad Air', 599, 699, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=640&h=480&fit=crop', 'Versatile tablet that balances performance and value. Features the M1 chip, beautiful display, and support for Apple Pencil and Magic Keyboard. Perfect for students, professionals, and creatives who want iPad Pro features at a more accessible price point.'],
                ['Samsung Galaxy Tab S9', 799, 899, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=640&h=480&fit=crop', 'Premium Android tablet with stunning AMOLED display, S Pen included, and powerful Snapdragon processor. Features water resistance, DeX mode for desktop-like productivity, and exceptional multimedia capabilities. The best Android tablet for productivity and entertainment.'],
                ['iPad Mini', 499, 599, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=640&h=480&fit=crop', 'Compact tablet perfect for reading, note-taking, and on-the-go productivity. Features A15 Bionic chip, support for Apple Pencil, and all-day battery life. Ideal for users who want iPad power in a portable, one-handed form factor.'],
                ['Microsoft Surface Pro 9', 999, 1199, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=640&h=480&fit=crop', 'The ultimate 2-in-1 device that transforms from tablet to laptop. Features Intel processors, detachable keyboard, and full Windows 11. Perfect for professionals who need a tablet for creativity and a laptop for productivity in one device.'],
                ['Samsung Galaxy Tab S9 Ultra', 1199, 1399, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=640&h=480&fit=crop', 'Massive 14.6-inch tablet designed for productivity and creativity. Features dual front cameras, S Pen included, and powerful performance. Perfect for professionals who need a large-screen tablet for multitasking, drawing, and content creation.'],
                ['iPad 10th Gen', 449, 549, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=640&h=480&fit=crop', 'Entry-level iPad with modern design and A14 Bionic chip. Features USB-C connectivity, support for Apple Pencil and Magic Keyboard, and all-day battery life. Perfect for students and first-time tablet users who want the iPad experience at an affordable price.'],
                ['Lenovo Tab P12', 399, 499, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=640&h=480&fit=crop', 'Large-screen Android tablet perfect for media consumption and light productivity. Features a 12.6-inch display, good battery life, and optional keyboard attachment. Great value for users who want a large tablet without the premium price tag.'],
                ['OnePlus Pad', 479, 579, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=640&h=480&fit=crop', 'Smooth Android tablet experience with OnePlus\'s signature design and performance. Features a high-refresh-rate display, fast charging, and clean software. Perfect for users who want a premium Android tablet experience with OnePlus\'s attention to detail.'],
                ['Amazon Fire Max 11', 229, null, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=640&h=480&fit=crop', 'Affordable large-screen tablet perfect for media consumption and Amazon services. Features an 11-inch display, all-day battery, and access to Amazon\'s ecosystem. Ideal for users who primarily use their tablet for streaming, reading, and basic tasks.'],
            ],
            'TVs' => [
                ['Samsung QLED 65"', 1299, 1599, 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=640&h=480&fit=crop', 'Premium QLED 4K TV with quantum dot technology delivering vibrant colors and exceptional brightness. Features smart TV capabilities, gaming mode, and HDR support. Perfect for movie enthusiasts and gamers who want stunning picture quality and smart features.'],
                ['LG OLED 55"', 1199, 1499, 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=640&h=480&fit=crop', 'Perfect black levels and infinite contrast with OLED technology. Features self-lit pixels, Dolby Vision IQ, and webOS smart platform. The ultimate choice for cinephiles who demand the best picture quality and want to experience movies as directors intended.'],
                ['Sony Bravia 75"', 1999, 2399, 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=640&h=480&fit=crop', 'Massive 75-inch 4K TV with Sony\'s Cognitive Processor XR for intelligent picture and sound optimization. Features Google TV, Acoustic Surface Audio, and exceptional upscaling. Perfect for large living rooms where you want an immersive viewing experience.'],
                ['TCL QLED 55"', 499, 699, 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=640&h=480&fit=crop', 'Excellent value QLED TV with quantum dot technology and Roku TV built-in. Features 4K HDR, voice control, and thousands of streaming channels. Perfect for budget-conscious buyers who want premium features without the premium price tag.'],
                ['Samsung Neo QLED 85"', 2999, 3499, 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=640&h=480&fit=crop', 'Flagship 85-inch TV with Mini LED backlighting for exceptional brightness and contrast control. Features 8K upscaling, Object Tracking Sound, and smart home integration. The ultimate home theater experience for those who want the absolute best.'],
                ['LG OLED 65"', 1799, 2199, 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=640&h=480&fit=crop', 'Larger OLED TV with perfect blacks and stunning picture quality. Features α9 AI Processor, Filmmaker Mode, and webOS. Perfect for serious home theater enthusiasts who want OLED quality in a larger size for immersive movie watching.'],
                ['Hisense ULED 55"', 599, 799, 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=640&h=480&fit=crop', 'Budget-friendly 4K TV with ULED technology for enhanced contrast and color. Features Google TV, voice control, and good picture quality. Great value for users who want a solid 4K TV experience without breaking the bank.'],
                ['Sony Bravia 65"', 1499, 1799, 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=640&h=480&fit=crop', 'Premium 65-inch TV with Sony\'s advanced processing and Acoustic Surface Audio technology. Features Google TV, excellent motion handling, and exceptional upscaling. Perfect for users who want Sony quality and smart features in a mid-size format.'],
                ['Vizio M-Series 50"', 399, 549, 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=640&h=480&fit=crop', 'Affordable 4K TV with good picture quality and smart features. Features Quantum Color technology, low input lag for gaming, and built-in Chromecast. Perfect for smaller rooms or as a secondary TV where you want quality without spending too much.'],
                ['TCL Roku TV 43"', 299, null, 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=640&h=480&fit=crop', 'Compact smart TV with Roku TV built-in for easy streaming. Features 4K resolution, voice control, and thousands of free channels. Perfect for bedrooms, kitchens, or small spaces where you want a smart TV experience at an unbeatable price.'],
            ],
            'Cameras' => [
                ['Canon EOS R5', 3899, 4299, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=640&h=480&fit=crop', 'Professional full-frame mirrorless camera with 45MP sensor, 8K video recording, and advanced autofocus system. Features in-body image stabilization, dual card slots, and weather sealing. The ultimate camera for professional photographers and videographers who demand the best.'],
                ['Sony A7 IV', 2499, 2799, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=640&h=480&fit=crop', 'Versatile full-frame mirrorless camera with 33MP sensor, 4K 60p video, and exceptional autofocus. Features real-time tracking, 10fps continuous shooting, and excellent low-light performance. Perfect for hybrid shooters who need both photo and video capabilities.'],
                ['Nikon Z6 III', 1999, 2299, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=640&h=480&fit=crop', 'Advanced full-frame mirrorless camera with 24MP sensor and excellent video capabilities. Features in-body stabilization, weather sealing, and Nikon\'s renowned color science. Perfect for photographers who want Nikon quality in a modern mirrorless system.'],
                ['Fujifilm X-T5', 1699, 1999, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=640&h=480&fit=crop', 'Retro-styled APS-C mirrorless camera with 40MP sensor and film simulation modes. Features weather sealing, dual card slots, and exceptional build quality. Perfect for photographers who appreciate classic design and Fujifilm\'s unique color rendering.'],
                ['Canon EOS R6', 2499, 2799, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=640&h=480&fit=crop', 'High-performance full-frame camera optimized for action and low-light photography. Features 20fps continuous shooting, advanced autofocus, and in-body stabilization. Perfect for sports, wildlife, and event photographers who need speed and reliability.'],
                ['Sony A7C', 1799, 2099, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=640&h=480&fit=crop', 'Compact full-frame mirrorless camera that doesn\'t compromise on image quality. Features 24MP sensor, excellent autofocus, and small form factor. Perfect for travel photographers and content creators who want full-frame quality in a portable package.'],
                ['Panasonic Lumix GH6', 1999, 2299, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=640&h=480&fit=crop', 'Video-focused Micro Four Thirds camera with 5.7K recording and advanced video features. Features V-Log, unlimited recording, and excellent stabilization. Perfect for videographers and filmmakers who prioritize video capabilities and need professional features.'],
                ['Olympus OM-1', 2199, 2499, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=640&h=480&fit=crop', 'Weather-sealed Micro Four Thirds camera with advanced computational photography. Features 50MP high-res mode, 120fps continuous shooting, and exceptional build quality. Perfect for outdoor and adventure photographers who need durability and performance.'],
                ['Canon PowerShot G7 X', 699, 799, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=640&h=480&fit=crop', 'Premium compact camera with large sensor and fast lens. Features 4K video, tilting touchscreen, and excellent image quality. Perfect for vloggers and travel photographers who want high quality in a pocketable form factor.'],
                ['GoPro Hero 12', 399, null, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=640&h=480&fit=crop', 'Action camera built for adventure with 5.3K video, HyperSmooth stabilization, and waterproof design. Features excellent image stabilization, time-lapse modes, and rugged construction. Perfect for athletes, adventurers, and anyone who wants to capture action from unique perspectives.'],
            ],
            'Smartwatches' => [
                ['Apple Watch Ultra 2', 799, 899, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=640&h=480&fit=crop', 'Apple\'s most rugged and capable smartwatch designed for extreme adventures. Features titanium construction, dual-frequency GPS, action button, and up to 60 hours of battery. Perfect for athletes, adventurers, and outdoor enthusiasts who need durability and advanced features.'],
                ['Apple Watch Series 9', 399, 499, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=640&h=480&fit=crop', 'Latest Apple Watch with S9 chip, brighter display, and double-tap gesture. Features advanced health tracking, crash detection, and seamless iPhone integration. Perfect for iPhone users who want the best smartwatch experience with comprehensive health and fitness features.'],
                ['Samsung Galaxy Watch 6', 299, 349, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=640&h=480&fit=crop', 'Premium Android smartwatch with advanced health monitoring and fitness tracking. Features rotating bezel, long battery life, and comprehensive health sensors. Perfect for Android users who want a feature-rich smartwatch with excellent health tracking capabilities.'],
                ['Garmin Fenix 7', 699, 799, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=640&h=480&fit=crop', 'Premium multisport GPS watch built for serious athletes. Features advanced training metrics, maps, and exceptional battery life. Perfect for runners, cyclists, and outdoor athletes who need detailed performance data and navigation capabilities.'],
                ['Apple Watch SE', 249, 299, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=640&h=480&fit=crop', 'Affordable Apple Watch with essential features. Features core health tracking, fitness features, and iPhone integration at a lower price point. Perfect for first-time smartwatch buyers or those who want Apple Watch features without the premium price tag.'],
                ['Fitbit Sense 2', 299, 349, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=640&h=480&fit=crop', 'Advanced health smartwatch with stress management and comprehensive health tracking. Features EDA sensor, skin temperature, and detailed sleep analysis. Perfect for users focused on health and wellness who want detailed insights into their body\'s metrics.'],
                ['Garmin Forerunner 955', 499, 599, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=640&h=480&fit=crop', 'Premium running watch with advanced training features and music storage. Features multi-band GPS, training readiness, and detailed running metrics. Perfect for serious runners who want comprehensive training data and performance insights.'],
                ['Samsung Galaxy Watch 6 Classic', 399, 449, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=640&h=480&fit=crop', 'Premium Android smartwatch with rotating bezel for intuitive navigation. Features advanced health sensors, long battery life, and premium design. Perfect for Android users who want a traditional watch feel with modern smartwatch capabilities.'],
                ['Amazfit GTR 4', 199, 249, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=640&h=480&fit=crop', 'Feature-rich smartwatch with exceptional battery life and comprehensive health tracking. Features GPS, heart rate monitoring, and up to 14 days of battery. Perfect for users who want smartwatch features with minimal charging requirements.'],
                ['Polar Vantage V3', 599, null, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=640&h=480&fit=crop', 'Advanced training watch with comprehensive performance metrics and recovery tracking. Features advanced heart rate technology, training load analysis, and excellent battery life. Perfect for serious athletes who want detailed training insights and recovery guidance.'],
            ],
            'Audio' => [
                ['Sonos Arc', 899, 999, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=640&h=480&fit=crop', 'Premium Dolby Atmos soundbar that delivers immersive cinematic audio. Features 11 drivers, voice control, and seamless multi-room audio integration. Perfect for home theater enthusiasts who want the best soundbar experience with smart home integration.'],
                ['Bose Soundbar 700', 799, 899, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=640&h=480&fit=crop', 'Premium soundbar with exceptional clarity and depth. Features ADAPTiQ audio calibration, voice control, and wireless subwoofer compatibility. Perfect for users who want Bose quality and smart features in a sleek soundbar design.'],
                ['Sonos Beam', 449, 549, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=640&h=480&fit=crop', 'Compact smart soundbar perfect for smaller rooms. Features Dolby Atmos, voice control, and seamless integration with other Sonos speakers. Perfect for apartment dwellers and users who want premium sound in a compact form factor.'],
                ['JBL Charge 5', 179, 229, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=640&h=480&fit=crop', 'Portable Bluetooth speaker with powerful bass and long battery life. Features IP67 waterproof rating, USB-C charging, and can charge your devices. Perfect for outdoor adventures, parties, and anyone who wants great sound on the go.'],
                ['Sonos Sub', 749, 849, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=640&h=480&fit=crop', 'Wireless subwoofer that adds deep, powerful bass to your Sonos system. Features force-canceling drivers and seamless wireless integration. Perfect for users who want to enhance their Sonos soundbar or speaker system with room-shaking bass.'],
                ['Bose Home Speaker 500', 399, 499, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=640&h=480&fit=crop', 'Premium smart speaker with 360-degree sound and voice control. Features six microphones for excellent voice recognition and Bose\'s signature sound quality. Perfect for users who want a high-quality smart speaker with exceptional audio performance.'],
                ['Sonos Move', 399, 449, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=640&h=480&fit=crop', 'Portable smart speaker that works indoors and outdoors. Features WiFi and Bluetooth, weather resistance, and up to 11 hours of battery. Perfect for users who want Sonos quality both at home and on the go with seamless switching.'],
                ['JBL Flip 6', 129, 179, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=640&h=480&fit=crop', 'Compact portable speaker with powerful sound and rugged design. Features IP67 waterproof rating, PartyBoost for stereo pairing, and 12 hours of battery. Perfect for beach trips, pool parties, and outdoor activities where you need durable, great-sounding audio.'],
                ['Audioengine A2+', 269, 329, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=640&h=480&fit=crop', 'Premium desktop speakers with exceptional sound quality and elegant design. Features built-in DAC, multiple inputs, and compact form factor. Perfect for desktop setups, home offices, and audiophiles who want high-quality sound in a compact package.'],
                ['KEF LS50 Wireless', 2199, null, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=640&h=480&fit=crop', 'Award-winning wireless speakers with exceptional sound quality and beautiful design. Features built-in amplification, multiple connectivity options, and KEF\'s Uni-Q driver technology. Perfect for audiophiles who want the best wireless speaker experience with studio-quality sound.'],
            ],
        ];

        foreach ($categories as $category) {
            $categoryName = $category->name;
            
            if (isset($productData[$categoryName])) {
                foreach ($productData[$categoryName] as $productInfo) {
                    [$name, $price, $originalPrice, $imageUrl, $description] = $productInfo;
                    
                    Product::create([
                        'name' => $name,
                        'price' => $price,
                        'original_price' => $originalPrice,
                        'image_url' => $imageUrl,
                        'description' => $description,
                        'category_id' => $category->id,
                    ]);
                }
            } else {
                // Fallback for any categories without specific data
                for ($i = 1; $i <= 10; $i++) {
                    Product::create([
                        'name' => $categoryName . ' Product ' . $i,
                        'price' => rand(100, 2000),
                        'original_price' => rand(200, 2500),
                        'image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=640&h=480&fit=crop&sig=' . $i,
                        'description' => 'High-quality ' . strtolower($categoryName) . ' product featuring premium materials, exceptional performance, and innovative design. Perfect for users who demand the best in their ' . strtolower($categoryName) . ' experience.',
                        'category_id' => $category->id,
                    ]);
                }
            }
        }
    }
}
